[package]
name = "fill_skeleton"
version = "0.1.0"
edition = "2021"
authors = ["Zekai Wang <q1203981754@hotmail.com>"]

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = { version = "0.19.7", features = ["lexer"] }
serde = "1.0"
serde_json = "1.0"