use crate::parser::*;

grammar;
match {_}

pub Program: Vec<Section> = <sections: (<Section>)*> => sections;

Spliter: String = "///" => <>.to_owned();

Section: Section = {
  <s1: Spliter> "start" <ident: Ident> <items: (<Item>)*> <s2: Spliter> "end" =>
    Section {ident, items, ignore: false},
}

Item: Item = {
  <Content> => Item::Content(<>),
  <Section> => Item::SubSection(<>),
}

Content: String = r"\n[^/]*/{0,2}[^/]+" => <>.to_owned();

Ident: String = r"[_a-zA-Z]\w*" => <>.to_owned();
